This alert was generated by Wordfence on "<?php echo $blogName; ?>" at <?php echo $date; ?>


<?php if(! $isPaid){ ?>
NOTE: Upgrading to the paid version of Wordfence gives you two factor authentication (sign-in via cellphone)
and country blocking which are both effective methods to block attacks.
Click here to sign-up for the Premium version of Wordfence now.
https://www.wordfence.com/wordfence-signup/

<?php } ?>

<?php echo $alertMsg; ?>
<?php if($IPMsg){ echo "\n$IPMsg\n"; } ?>

--
To change your alert options for Wordfence, visit:
<?php echo $myOptionsURL; ?>

To see current Wordfence alerts, visit:
<?php echo $myHomeURL; ?>



